import 'package:yeni_oyun_sablon/core/database/models/item_set_model.dart';

/// Oyunun 5 Kat Genişletilmiş, Kademeli ve Derinlikli Koleksiyon/Sinerji Setleri Kataloğu (35 Devasa Set)
class GameItemSets {
  static const List<ItemSetModel> all = [
    // =========================================================================
    // 1. MÜZİK, SANAT & ANTİKA KOLEKSİYONLARI (Kültür & Prestij)
    // =========================================================================
    ItemSetModel(
      id: 'set_vintage_rock_band',
      nameTr: '1970 Vintage Rock Stüdyosu',
      nameEn: '1970s Vintage Rock Band Studio',
      descriptionTr: 'Analog sesin altın çağından kalma elektro gitar, akustik gitar, saksafon, trampet ve tef takımı.',
      descriptionEn: 'The analog golden era studio collection featuring vintage guitars, brass saxophone, snare and tambourine.',
      loreTr: 'Woodstock festivalinin efsanevi tonlarını barındıran bu enstrümanlar, koleksiyonerler için paha biçilemez bir hazinedir.',
      loreEn: 'Holding the legendary tones of the 1970s rock movement, these pristine instruments command extraordinary auction value.',
      category: 'muzik_aletleri',
      rarity: SetRarity.epic,
      requiredItemCodes: [
        'muzik_aletleri_elektro_gitar',
        'muzik_aletleri_akustik_gitar',
        'muzik_aletleri_saksafon',
        'muzik_aletleri_trampet',
        'muzik_aletleri_tef',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 1.55,
      cashReward: 2500,
      reputationReward: 650,
      badgeIcon: 'music_note',
      passivePerkCode: 'rock_legend_aura',
      tierPerks: [
        SetTierPerk(
          requiredCount: 2,
          titleTr: 'Analog Akort',
          titleEn: 'Analog Tune',
          descriptionTr: 'Müzik aletlerinin satış değeri +%15 artar.',
          descriptionEn: 'Musical instruments sell for +15% more.',
          bonusMultiplier: 1.15,
        ),
        SetTierPerk(
          requiredCount: 4,
          titleTr: 'Plak Şirketi Sözleşmesi',
          titleEn: 'Record Deal',
          descriptionTr: 'Müzayede satışlarında +%35 kâr ve +100 itibar.',
          descriptionEn: '+35% profit on all auctions and +100 reputation.',
          bonusMultiplier: 1.35,
        ),
      ],
    ),

    ItemSetModel(
      id: 'set_victorian_antique_parlor',
      nameTr: 'Viktorya Dönemi Aristokrat Salonu',
      nameEn: 'Victorian Aristocrat Salon Suite',
      descriptionTr: 'Yağlı boya tablo, Roma büstü, pirinç gramofon, şömine saati, gümüş şamdan ve porselen vazo.',
      descriptionEn: 'Oil painting, marble bust, brass gramophone, mantel clock, silver candelabra and fine porcelain vase.',
      loreTr: '19. yüzyıl soylu malikanelerinden miras kalan bu antikalar, müze küratörlerinin açık artırmalarda çılgınca yarıştığı parçalardır.',
      loreEn: 'Preserved from noble manors of the 19th century, curated by international historic museum auctions.',
      category: 'sanat_antikalar',
      rarity: SetRarity.legendary,
      requiredItemCodes: [
        'sanat_antikalar_yagli_boya_tablo',
        'sanat_antikalar_roma_bustu',
        'sanat_antikalar_gramofon',
        'sanat_antikalar_somine_saati',
        'sanat_antikalar_samdan',
        'sanat_antikalar_porselen_vazo',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 1.70,
      cashReward: 4000,
      reputationReward: 900,
      badgeIcon: 'museum',
      passivePerkCode: 'aristocrat_influence',
      tierPerks: [
        SetTierPerk(
          requiredCount: 3,
          titleTr: 'Antikacı Sertifikası',
          titleEn: 'Antique Certificate',
          descriptionTr: 'Antika eşyalarda ekspertiz maliyeti sıfırlanır.',
          descriptionEn: 'Appraisal fee waived for all antique pieces.',
          bonusMultiplier: 1.25,
        ),
      ],
    ),

    ItemSetModel(
      id: 'set_jazz_club_ensemble',
      nameTr: 'Geceyarısı Caz Kulübü Orkestrası',
      nameEn: 'Midnight Jazz Club Ensemble',
      descriptionTr: 'Trompet, saksafon, klarnet, akordeon ve cebe sığan mızıka.',
      descriptionEn: 'Brass trumpet, saxophone, dark clarinet, accordion and pocket blues harmonica.',
      category: 'muzik_aletleri',
      rarity: SetRarity.rare,
      requiredItemCodes: [
        'muzik_aletleri_trompet',
        'muzik_aletleri_saksafon',
        'muzik_aletleri_klarnet',
        'muzik_aletleri_akordeon',
        'muzik_aletleri_mizika',
      ],
      bonusType: SetBonusType.reputationMultiplier,
      bonusMultiplier: 1.45,
      cashReward: 1800,
      reputationReward: 450,
      badgeIcon: 'nightlife',
    ),

    ItemSetModel(
      id: 'set_renaissance_study',
      nameTr: 'Rönesans Filozof & Bilgin Odası',
      nameEn: 'Renaissance Philosopher Study',
      descriptionTr: 'Ahşap kitaplık, masa küresi, hokka ve tüy kalem, şömine saati ve oyma sandalye.',
      descriptionEn: 'Carved bookshelf, antique desk globe, feather quill inkpot, mantel clock and carved chair.',
      category: 'ahsap_mobilya',
      rarity: SetRarity.rare,
      requiredItemCodes: [
        'ahsap_mobilya_kitaplik',
        'sanat_antikalar_masa_kuresi',
        'sanat_antikalar_hokka_kalem',
        'sanat_antikalar_somine_saati',
        'ahsap_mobilya_sandalye',
      ],
      bonusType: SetBonusType.reputationMultiplier,
      bonusMultiplier: 1.40,
      cashReward: 1600,
      reputationReward: 400,
      badgeIcon: 'auto_stories',
    ),

    // =========================================================================
    // 2. CASUSLUK, SOYGUN & GİZLİ OPERASYON (Covert Ops & Heist)
    // =========================================================================
    ItemSetModel(
      id: 'set_master_lockpick_heist',
      nameTr: 'Kusursuz Kasa Soygun Takımı',
      nameEn: 'Master Safe-Cracking Heist Kit',
      descriptionTr: 'Deri kılıflı maymuncuk seti, kasa stetoskobu, cam kesici, sessiz karbon matkap ve UV fener.',
      descriptionEn: 'Leather lockpick pouch, stethoscope, circular glass cutter, cordless quiet drill and UV blacklight.',
      loreTr: 'En ağır çelik kombinasyon kasalarını bile iz bırakmadan açabilen profesyonel hırsızlar loncasının teçhizatı.',
      loreEn: 'Used by the underground guild to silently crack bank vaults and bypass electronic magnetic sensors.',
      category: 'kilit_ve_hirsizlik',
      rarity: SetRarity.legendary,
      requiredItemCodes: [
        'kilit_ve_hirsizlik_deri_kilifli_maymuncuk_seti',
        'kilit_ve_hirsizlik_kasa_stetoskobu',
        'kilit_ve_hirsizlik_cam_vantuzlu_kesici',
        'kilit_ve_hirsizlik_sessiz_akulu_matkap',
        'kilit_ve_hirsizlik_uv_mor_otesisi_fener',
      ],
      bonusType: SetBonusType.specialAccess,
      bonusMultiplier: 1.65,
      cashReward: 3500,
      reputationReward: 800,
      badgeIcon: 'lock_open',
      passivePerkCode: 'bypass_vault_locks', // Kasaları anında açar
      tierPerks: [
        SetTierPerk(
          requiredCount: 3,
          titleTr: 'Sessiz Giriş',
          titleEn: 'Silent Entry',
          descriptionTr: 'Kilitli kutuları açarken alarm/hasar riski kalkar.',
          descriptionEn: 'Locks on storage boxes cannot trigger traps or damage loot.',
          bonusMultiplier: 1.25,
        ),
      ],
    ),

    ItemSetModel(
      id: 'set_cold_war_spy_agent',
      nameTr: 'Soğuk Savaş Ajanı & Gölge Muhbir',
      nameEn: 'Cold War Covert Field Operative',
      descriptionTr: 'Sahte kimlik cüzdanı, şifre kırıcı dekoder, taktik telsiz, sis bombası ve çelik tel kanca.',
      descriptionEn: 'Hidden badge wallet, cipher frequency decoder, tactical radio, smoke canister and grappling hook.',
      category: 'kilit_ve_hirsizlik',
      rarity: SetRarity.epic,
      requiredItemCodes: [
        'kilit_ve_hirsizlik_sahte_kimlik_cuzdani',
        'kilit_ve_hirsizlik_sifre_kirici_dekoder',
        'taktik_hayatta_kalma_telsiz',
        'kilit_ve_hirsizlik_sis_bombasi',
        'kilit_ve_hirsizlik_celik_tel_kanca',
      ],
      bonusType: SetBonusType.raidLuckBonus,
      bonusMultiplier: 1.50,
      cashReward: 2600,
      reputationReward: 600,
      badgeIcon: 'security',
      passivePerkCode: 'stealth_infiltrator',
    ),

    ItemSetModel(
      id: 'set_spec_ops_tactical',
      nameTr: 'Özel Kuvvetler Taktik Operasyon',
      nameEn: 'Spec-Ops Heavy Tactical Unit',
      descriptionTr: 'Dürbünlü tüfek, 9mm tabanca, av bıçağı, tomahawk balta ve el bombası.',
      descriptionEn: 'Sniper rifle, 9mm pistol, steel combat knife, tomahawk axe and tactical grenade.',
      category: 'gercekci_silahlar',
      rarity: SetRarity.epic,
      requiredItemCodes: [
        'gercekci_silahlar_durbunlu_tufek',
        'gercekci_silahlar_9mm_tabanca',
        'gercekci_silahlar_av_bicagi',
        'gercekci_silahlar_tomahawk_balta',
        'gercekci_silahlar_el_bombasi',
      ],
      bonusType: SetBonusType.bargainMastery,
      bonusMultiplier: 1.45,
      cashReward: 2400,
      reputationReward: 550,
      badgeIcon: 'military_tech',
      passivePerkCode: 'intimidate_rivals', // Müzayedede rakipleri korkutup çekilmeye zorlar
    ),

    ItemSetModel(
      id: 'set_wasteland_survivalist',
      nameTr: 'Kıyamet Sonrası Hayatta Kalma (Survivalist)',
      nameEn: 'Post-Apocalyptic Survivalist Loadout',
      descriptionTr: 'Taktik sırt çantası, askeri gaz maskesi, çelik matara, turnike ve lensatik pusula.',
      descriptionEn: 'Tactical backpack, military gas mask, canteen flask, tourniquet and compass.',
      category: 'taktik_hayatta_kalma',
      rarity: SetRarity.rare,
      requiredItemCodes: [
        'taktik_hayatta_kalma_sirt_cantasi',
        'taktik_hayatta_kalma_gaz_maskesi',
        'taktik_hayatta_kalma_matara',
        'tip_ve_saglik_turnike',
        'taktik_hayatta_kalma_pusula',
      ],
      bonusType: SetBonusType.specialAccess,
      bonusMultiplier: 1.35,
      cashReward: 1500,
      reputationReward: 350,
      badgeIcon: 'backpack',
      passivePerkCode: 'toxic_gas_immunity', // Zehirli gazlı depolara hasarsız giriş
    ),

    // =========================================================================
    // 3. MUTFAK & GASTRONOMİ (Culinary & Fine Dining)
    // =========================================================================
    ItemSetModel(
      id: 'set_gourmet_master_chef',
      nameTr: 'Michelin Yıldızlı Gourmet Mutfak',
      nameEn: 'Michelin-Star Gourmet Culinary Suite',
      descriptionTr: 'Döküm demir tava, el dövmesi bakır tencere, semaver, şef bıçağı ve beyaz mermer havan.',
      descriptionEn: 'Heavy cast-iron skillet, hammered copper pot, brass samovar, chef knife and marble mortar.',
      loreTr: 'Paris ve İstanbul saray mutfaklarının asırlık lezzet sırlarını barındıran üst düzey zanaat mutfak takımı.',
      loreEn: 'Hand-hammered culinary tools revered by five-star restaurant chains and luxury hotel auctions.',
      category: 'mutfak_gastronomi',
      rarity: SetRarity.legendary,
      requiredItemCodes: [
        'mutfak_gastronomi_dokum_demir_tava',
        'mutfak_gastronomi_bakir_tencere',
        'mutfak_gastronomi_bakir_semaver',
        'mutfak_gastronomi_sef_bicagi',
        'mutfak_gastronomi_mermer_havan',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 1.60,
      cashReward: 3000,
      reputationReward: 700,
      badgeIcon: 'restaurant',
      passivePerkCode: 'culinary_mastery',
      tierPerks: [
        SetTierPerk(
          requiredCount: 3,
          titleTr: 'Şef Tavsiyesi',
          titleEn: 'Chef Specialty',
          descriptionTr: 'Mutfak eşyaları satışında +%25 prim.',
          descriptionEn: '+25% sale premium on all culinary items.',
          bonusMultiplier: 1.25,
        ),
      ],
    ),

    ItemSetModel(
      id: 'set_traditional_coffeehouse',
      nameTr: 'Tarihi Kahvehane & Çay Ocağı',
      nameEn: 'Historic Tea & Turkish Coffee Parlor',
      descriptionTr: 'Antika bakır semaver, pirinç kollu el kahve değirmeni, porselen tabak seti ve ahşap oklava.',
      descriptionEn: 'Antique copper samovar, hand-crank brass coffee grinder, gilded plates and solid rolling pin.',
      category: 'mutfak_gastronomi',
      rarity: SetRarity.rare,
      requiredItemCodes: [
        'mutfak_gastronomi_bakir_semaver',
        'mutfak_gastronomi_el_kahve_degirmeni',
        'mutfak_gastronomi_porselen_tabak_seti',
        'mutfak_gastronomi_ahsap_oklava',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 1.35,
      cashReward: 1400,
      reputationReward: 350,
      badgeIcon: 'local_cafe',
    ),

    ItemSetModel(
      id: 'set_butcher_prep_station',
      nameTr: 'Usta Kasap & Şarküteri İstasyonu',
      nameEn: 'Master Butcher & Cleaver Station',
      descriptionTr: 'Dövme çelik kasap satırı, döküm tava, şef bıçağı, mermer havan ve ceviz biber değirmeni.',
      descriptionEn: 'Forged meat cleaver, cast iron skillet, chef knife, marble mortar and walnut pepper mill.',
      category: 'mutfak_gastronomi',
      rarity: SetRarity.rare,
      requiredItemCodes: [
        'mutfak_gastronomi_et_satiri',
        'mutfak_gastronomi_dokum_demir_tava',
        'mutfak_gastronomi_sef_bicagi',
        'mutfak_gastronomi_mermer_havan',
        'mutfak_gastronomi_biber_ogutucu',
      ],
      bonusType: SetBonusType.workshopSpeed,
      bonusMultiplier: 1.30,
      cashReward: 1300,
      reputationReward: 300,
      badgeIcon: 'kebab_dining',
    ),

    // =========================================================================
    // 4. OTO SANAYİ, MEKANİK & MOTOR REVİZYONU (Automotive & Street Racing)
    // =========================================================================
    ItemSetModel(
      id: 'set_master_mechanic_garage',
      nameTr: 'Usta Oto Tamirhanesi',
      nameEn: 'Master Automotive Repair Garage',
      descriptionTr: 'V8 motor bloğu, kırmızı alet çantası, lokma seti, ateşleme bujisi ve dinamo jeneratörü.',
      descriptionEn: 'V8 engine block, red metal toolbox, socket set, glow plug and alternator dynamo.',
      loreTr: 'Klasik Amerikan kaslı araçlarının kalbini yeniden attıran bu motor takımı, sokak yarışçılarının rüyasıdır.',
      loreEn: 'Rebuilding high-compression muscle engines, giving unbeatable speed to the workshop operations.',
      category: 'araba_parcalari',
      rarity: SetRarity.epic,
      requiredItemCodes: [
        'araba_parcalari_v8_motor_blogu',
        'manuel_el_aletleri_kirmizi_alet_cantasi',
        'manuel_el_aletleri_lokma_seti',
        'araba_parcalari_buji',
        'agir_sanayi_dinamo',
      ],
      bonusType: SetBonusType.workshopSpeed,
      bonusMultiplier: 1.50,
      cashReward: 2500,
      reputationReward: 600,
      badgeIcon: 'build',
      passivePerkCode: 'overclock_workshop', // Atölye işlem süresi yarı yarıya düşer
      tierPerks: [
        SetTierPerk(
          requiredCount: 3,
          titleTr: 'Hızlı Söküm',
          titleEn: 'Rapid Teardown',
          descriptionTr: 'Demontaj işlemlerinde parça kaybı önlenir.',
          descriptionEn: 'Prevents component destruction during salvage.',
          bonusMultiplier: 1.20,
        ),
      ],
    ),

    ItemSetModel(
      id: 'set_street_drag_racer',
      nameTr: 'Pist Canavarı & Drag Yarışçısı',
      nameEn: 'Underground Street Drag Racer',
      descriptionTr: 'Yarış koltuğu, turboşarj, alaşım jant, amortisör ve yarış direksiyonu.',
      descriptionEn: 'Bucket racing seat, twin turbocharger, alloy rim, coilover shock and sports steering wheel.',
      category: 'araba_parcalari',
      rarity: SetRarity.epic,
      requiredItemCodes: [
        'araba_parcalari_yaris_koltugu',
        'araba_parcalari_turbosarj',
        'araba_parcalari_alasim_jant',
        'araba_parcalari_amortisor',
        'araba_parcalari_yaris_direksiyonu',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 1.45,
      cashReward: 2200,
      reputationReward: 500,
      badgeIcon: 'directions_car',
    ),

    ItemSetModel(
      id: 'set_heavy_industrial_plant',
      nameTr: 'Ağır Sanayi Santrali & Hidrolik Güç',
      nameEn: 'Heavy Industrial Power Plant',
      descriptionTr: 'Ağır elektrik motoru, hidrolik piston, döküm dişli çark, vinç zinciri ve buhar vanası.',
      descriptionEn: 'Large electric motor, hydraulic cylinder piston, massive cogwheel, hoist chain and steam valve.',
      category: 'agir_sanayi',
      rarity: SetRarity.legendary,
      requiredItemCodes: [
        'agir_sanayi_elektrik_motoru',
        'agir_sanayi_hidrolik_piston',
        'agir_sanayi_disli_cark',
        'agir_sanayi_vinc_zinciri',
        'agir_sanayi_buhar_vanasi',
      ],
      bonusType: SetBonusType.workshopSpeed,
      bonusMultiplier: 1.60,
      cashReward: 3600,
      reputationReward: 850,
      badgeIcon: 'precision_manufacturing',
      passivePerkCode: 'titan_salvage', // Büyük makineleri sökebilme yetkisi
    ),

    // =========================================================================
    // 5. TIP, BİYOLOJİ & SAĞLIK (Medical & Emergency Rescue)
    // =========================================================================
    ItemSetModel(
      id: 'set_trauma_field_medic',
      nameTr: 'Acil Travma & Sahra Sıhhiye Donanımı',
      nameEn: 'Emergency Trauma & Field Medic Suite',
      descriptionTr: 'Taşınabilir AED defibrilatör, metal saha sandığı, titanyum neşter kiti ve stetoskop.',
      descriptionEn: 'Portable AED defibrillator, military trauma chest, titanium scalpel kit and stethoscope.',
      loreTr: 'Zorlu saha kurtarma operasyonlarında hayat kurtaran cerrahi kalitede steril ekipmanlar.',
      loreEn: 'Tactical medical response apparatus certified for disaster and hazard search operations.',
      category: 'tip_ve_saglik',
      rarity: SetRarity.epic,
      requiredItemCodes: [
        'tip_ve_saglik_tasinabilir_defibrilator',
        'tip_ve_saglik_metal_ilk_yardim_cantasi',
        'tip_ve_saglik_cerrahi_nester_seti',
        'tip_ve_saglik_tibbi_stetoskop',
      ],
      bonusType: SetBonusType.specialAccess,
      bonusMultiplier: 1.45,
      cashReward: 2400,
      reputationReward: 600,
      badgeIcon: 'medical_services',
      passivePerkCode: 'field_medic_protection',
    ),

    ItemSetModel(
      id: 'set_clinical_surgery_ward',
      nameTr: 'Klinik Cerrahi & Teşhis İstasyonu',
      nameEn: 'Clinical Surgery & Diagnostic Ward',
      descriptionTr: 'Dijital tansiyon ölçer, otoskop fener, ilaç ampulleri standı, turnike ve cerrahi makas.',
      descriptionEn: 'Digital BP monitor, diagnostic otoscope, medicine ampoules rack, tourniquet and dissection scissors.',
      category: 'tip_ve_saglik',
      rarity: SetRarity.rare,
      requiredItemCodes: [
        'tip_ve_saglik_dijital_tansiyon_aleti',
        'tip_ve_saglik_otoskop_muayene_feneri',
        'tip_ve_saglik_ilac_ampul_seti',
        'tip_ve_saglik_turnike',
        'tip_ve_saglik_cerrahi_makas',
      ],
      bonusType: SetBonusType.reputationMultiplier,
      bonusMultiplier: 1.35,
      cashReward: 1600,
      reputationReward: 400,
      badgeIcon: 'healing',
    ),

    // =========================================================================
    // 6. SİMYA, KİMYA & LABORATUVAR (Alchemy, Reagents & Gems)
    // =========================================================================
    ItemSetModel(
      id: 'set_alchemy_high_laboratory',
      nameTr: 'Kadim Hermetik Simya Laboratuvarı',
      nameEn: 'Grand Hermetic Alchemy Laboratory',
      descriptionTr: 'Damıtma imbiği, pirinç mikroskop, erlenmayer, ametist geodu ve külçe altın.',
      descriptionEn: 'Distillation glass apparatus, microscope, erlenmeyer flask, amethyst geode and gold bullion.',
      loreTr: 'Metali altına dönüştüren ve felsefe taşının gizemlerini araştıran kadim simyacıların kutsal donanımı.',
      loreEn: 'The sacred tools of master alchemists seeking the philosopher stone and universal transmutation.',
      category: 'laboratuvar_simya',
      rarity: SetRarity.legendary,
      requiredItemCodes: [
        'laboratuvar_simya_damitma_imbigi',
        'laboratuvar_simya_mikroskop',
        'laboratuvar_simya_erlenmayer',
        'maden_ve_taslar_ametist_geodu',
        'maden_ve_taslar_kulce_altin',
      ],
      bonusType: SetBonusType.reputationMultiplier,
      bonusMultiplier: 1.75,
      cashReward: 4500,
      reputationReward: 1100,
      badgeIcon: 'science',
      passivePerkCode: 'transmutation_perk', // Hurda metalleri külçeye dönüştürme şansı
      tierPerks: [
        SetTierPerk(
          requiredCount: 3,
          titleTr: 'Simya Arıtımı',
          titleEn: 'Alchemy Purity',
          descriptionTr: 'Maden ve taş satışlarında +%30 değer artışı.',
          descriptionEn: '+30% sale value on precious metals and gems.',
          bonusMultiplier: 1.30,
        ),
      ],
    ),

    ItemSetModel(
      id: 'set_precious_bullion_vault',
      nameTr: 'Kraliyet Külçe & Maden Kasası',
      nameEn: 'Royal Precious Bullion Vault',
      descriptionTr: 'Külçe altın, gümüş külçe, titanyum blok, bakır külçe ve meteorit cevheri.',
      descriptionEn: 'Stack of gold ingots, refined silver bar, titanium block, copper ingot and black meteorite ore.',
      category: 'maden_ve_taslar',
      rarity: SetRarity.epic,
      requiredItemCodes: [
        'maden_ve_taslar_kulce_altin',
        'maden_ve_taslar_gumus_kulce',
        'maden_ve_taslar_titanyum_blok',
        'maden_ve_taslar_bakir_kulce',
        'maden_ve_taslar_meteorit_cevheri',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 1.55,
      cashReward: 3200,
      reputationReward: 750,
      badgeIcon: 'monetization_on',
    ),

    ItemSetModel(
      id: 'set_uncut_gemstone_cluster',
      nameTr: 'Paha Biçilemez Nadir Mücevher Yatağı',
      nameEn: 'Priceless Raw Gemstone Cluster',
      descriptionTr: 'Ham yakut, kesilmemiş zümrüt, parlak elmas, ametist geodu ve uranyum çubuğu.',
      descriptionEn: 'Rough ruby, uncut green emerald, brilliant cut diamond, purple amethyst geode and uranium rod.',
      category: 'maden_ve_taslar',
      rarity: SetRarity.mythic,
      requiredItemCodes: [
        'maden_ve_taslar_ham_yakut',
        'maden_ve_taslar_kesilmemis_zumrut',
        'maden_ve_taslar_parlak_elmas',
        'maden_ve_taslar_ametist_geodu',
        'maden_ve_taslar_uranyum_cubugu',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 2.0, // x2 Tam değer
      cashReward: 6000,
      reputationReward: 1500,
      badgeIcon: 'diamond',
      passivePerkCode: 'gemologist_radiance',
    ),

    // =========================================================================
    // 7. ZIRHLAR & SAVAŞ TARİHİ (Gladiator, Knight & Exoskeleton)
    // =========================================================================
    ItemSetModel(
      id: 'set_bronze_gladiator',
      nameTr: 'Antik Bronz Gladyatör Zırhı',
      nameEn: 'Ancient Bronze Gladiator Armor',
      descriptionTr: 'Bakır göğüslük, Sparta miğferi, yuvarlak kalkan ve bronz eldiven.',
      descriptionEn: 'Hammered copper cuirass, bronze spartan helmet, round bronze shield and riveted gauntlets.',
      category: 'tier1_bronz_zirh',
      rarity: SetRarity.rare,
      requiredItemCodes: [
        'tier1_bronz_zirh_bakir_gogusluk',
        'tier1_bronz_zirh_sparta_migferi',
        'tier1_bronz_zirh_yuvarlak_kalkan',
        'tier1_bronz_zirh_bronz_eldiven',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 1.40,
      cashReward: 2000,
      reputationReward: 500,
      badgeIcon: 'shield',
    ),

    ItemSetModel(
      id: 'set_medieval_steel_knight',
      nameTr: 'Ortaçağ Ağır Çelik Şövalye Takımı',
      nameEn: 'Hardened Steel Knight Plate Armor',
      descriptionTr: 'Çelik göğüslük, vizörlü kask, çelik boyunluk, kule kalkanı ve çelik çizme.',
      descriptionEn: 'Polished steel breastplate, bascinet visor helmet, steel gorget collar, kite shield and plate sabatons.',
      category: 'tier2_celik_zirh',
      rarity: SetRarity.epic,
      requiredItemCodes: [
        'tier2_celik_zirh_celik_gogusluk',
        'tier2_celik_zirh_vizorlu_kask',
        'tier2_celik_zirh_celik_boyunluk',
        'tier2_celik_zirh_kule_kalkani',
        'tier2_celik_zirh_celik_cizme',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 1.55,
      cashReward: 3000,
      reputationReward: 700,
      badgeIcon: 'security',
    ),

    ItemSetModel(
      id: 'set_titanium_exoskeleton_soldier',
      nameTr: 'Titanyum Dış İskelet & Ağır Zırh',
      nameEn: 'Titanium Exoskeleton Combat Armor',
      descriptionTr: 'Balistik yelek, titanyum göğüslük, karbon kask, dış iskelet bacak ve enerji kolçağı.',
      descriptionEn: 'Tactical ballistic breastplate, titanium cuirass, carbon helmet, exoskeleton leg and energy bracer.',
      loreTr: 'Geleceğin savaş alanları için geliştirilmiş, taşıma kapasitesini ve dayanıklılığı artıran sibernetik dış iskelet.',
      loreEn: 'High-tech powered exoskeleton boosting payload capacity and protecting against hazardous environments.',
      category: 'tier3_titanyum_zirh',
      rarity: SetRarity.legendary,
      requiredItemCodes: [
        'tier3_titanyum_zirh_balistik_yelek',
        'tier3_titanyum_zirh_titanyum_gogusluk',
        'tier3_titanyum_zirh_karbon_kask',
        'tier3_titanyum_zirh_dis_iskelet_bacak',
        'tier3_titanyum_zirh_enerji_kolcagi',
      ],
      bonusType: SetBonusType.workshopSpeed,
      bonusMultiplier: 1.65,
      cashReward: 4200,
      reputationReward: 950,
      badgeIcon: 'smart_toy',
      passivePerkCode: 'heavy_load_carrier', // Bagaj ağırlık sınırını +%30 artırır
    ),

    // =========================================================================
    // 8. BÜYÜLÜ & MELEZ ARCANE-TECH (Fantasy & Cyber-Magic)
    // =========================================================================
    ItemSetModel(
      id: 'set_arcane_archmage_regalia',
      nameTr: 'Kadim Başbüyücü Hazine Takımı',
      nameEn: 'Ancient Archmage Mystic Regalia',
      descriptionTr: 'Rünlü kılıç, büyü asası, alevli hançer, kristal yay ve sihirli kese.',
      descriptionEn: 'Engraved runic greatsword, ancient staff, flaming dagger, frosted crystal bow and mystic pouch.',
      category: 'buyulu_silahlar',
      rarity: SetRarity.legendary,
      requiredItemCodes: [
        'buyulu_silahlar_runlu_kilic',
        'buyulu_silahlar_buyu_asasi',
        'buyulu_silahlar_alevli_hancer',
        'buyulu_silahlar_kristal_yay',
        'buyulu_zirhlar_sihirli_kese',
      ],
      bonusType: SetBonusType.reputationMultiplier,
      bonusMultiplier: 1.80,
      cashReward: 4800,
      reputationReward: 1200,
      badgeIcon: 'auto_fix_high',
      passivePerkCode: 'arcane_enchantment',
    ),

    ItemSetModel(
      id: 'set_cyber_arcane_hybrid',
      nameTr: 'Siber-Rünik Arcane-Tech Başyapıtı',
      nameEn: 'Cybernetic Arcane-Tech Fusion',
      descriptionTr: 'Plazma tüfek, büyü parşömeni, ışın katanası, reaktör çekirdeği ve sibernetik el.',
      descriptionEn: 'Plasma runic rifle, digital ancient scroll, neon beam katana, energy reactor core and cybernetic hand.',
      loreTr: 'Siber teknoloji ile kadim büyü rünlerinin kaynaştığı yasak askeri prototip takımı.',
      loreEn: 'Forbidden military prototypes blending cyberware nano-circuits with forgotten dragon runes.',
      category: 'melez_arcane_tech',
      rarity: SetRarity.mythic,
      requiredItemCodes: [
        'melez_arcane_tech_plazma_tufek',
        'melez_arcane_tech_buyu_parsomeni',
        'melez_arcane_tech_isin_katanasi',
        'melez_arcane_tech_reaktor_cekirdegi',
        'melez_arcane_tech_sibernetik_el',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 2.20,
      cashReward: 7500,
      reputationReward: 2000,
      badgeIcon: 'bolt',
      passivePerkCode: 'singularity_reactor',
    ),

    ItemSetModel(
      id: 'set_royal_talisman_crown',
      nameTr: 'Kraliyet Tılsımları & Mücevherat',
      nameEn: 'Crown Jewels & Arcane Talismans',
      descriptionTr: 'Zümrüt kolye, safir küpe, gümüş bileklik, yakut yüzük ve koruyucu tılsım.',
      descriptionEn: 'Emerald necklace, sapphire earrings, silver cuff bracelet, ruby signet ring and protective talisman.',
      category: 'buyulu_takilar',
      rarity: SetRarity.epic,
      requiredItemCodes: [
        'buyulu_takilar_zumrut_kolye',
        'buyulu_takilar_safir_kupe',
        'buyulu_takilar_gumus_bileklik',
        'buyulu_takilar_yakut_yuzuk',
        'buyulu_takilar_koruyucu_tilsim',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 1.60,
      cashReward: 3200,
      reputationReward: 800,
      badgeIcon: 'auto_awesome',
    ),

    // =========================================================================
    // 9. ELEKTRONİK, OFİS & RETRO TEKNOLOJİ (Retro Computing & Hardware)
    // =========================================================================
    ItemSetModel(
      id: 'set_retro_80s_hacker_den',
      nameTr: '1980 Silikon Vadisi Hacker Odası',
      nameEn: '1980s Silicon Valley Hacker Den',
      descriptionTr: 'Tüplü CRT televizyon, masaüstü PC kasası, monitör, mekanik klavye ve optik mouse.',
      descriptionEn: 'Retro CRT TV, desktop tower PC, widescreen monitor, mechanical keyboard and mouse.',
      category: 'ofis_ekipmanlari',
      rarity: SetRarity.rare,
      requiredItemCodes: [
        'beyaz_esya_tuplu_tv',
        'ofis_ekipmanlari_pc_kasasi',
        'ofis_ekipmanlari_monitor',
        'ofis_ekipmanlari_klavye',
        'ofis_ekipmanlari_mouse',
      ],
      bonusType: SetBonusType.reputationMultiplier,
      bonusMultiplier: 1.40,
      cashReward: 1900,
      reputationReward: 450,
      badgeIcon: 'terminal',
    ),

    ItemSetModel(
      id: 'set_precision_crafting_hardware',
      nameTr: 'Zanaat Tezgâhı Çekirdek Donanımları',
      nameEn: 'Precision Crafting Hardware Bench',
      descriptionTr: 'Tezgâh mengenesi, lehim istasyonu, mikrometre kumpas ve torna aynası.',
      descriptionEn: 'Heavy bench vise, SMD soldering station, micrometer caliper and miniature lathe chuck.',
      category: 'tezgah_donanimlari',
      rarity: SetRarity.rare,
      requiredItemCodes: [
        'tezgah_donanimlari_tezgah_mengenesi',
        'tezgah_donanimlari_lehim_istasyonu',
        'tezgah_donanimlari_mikrometre_kumpas',
        'tezgah_donanimlari_torna_aynasi',
      ],
      bonusType: SetBonusType.workshopSpeed,
      bonusMultiplier: 1.40,
      cashReward: 1700,
      reputationReward: 420,
      badgeIcon: 'handyman',
    ),

    ItemSetModel(
      id: 'set_electrician_power_tools',
      nameTr: 'Elektrikçi & Ağır Elektronik Alet Seti',
      nameEn: 'Heavy Duty Electrician Power Tool Kit',
      descriptionTr: 'Darbeli matkap, sıcak hava tabancası, multimetre, taşlama makinesi ve dekupaj testere.',
      descriptionEn: 'Cordless impact drill, heat gun, digital multimeter, angle grinder and jigsaw.',
      category: 'elektronik_aletler',
      rarity: SetRarity.rare,
      requiredItemCodes: [
        'elektronik_aletler_darbeli_matkap',
        'elektronik_aletler_sicak_hava_tabancasi',
        'elektronik_aletler_multimetre',
        'elektronik_aletler_taslama_makinesi',
        'elektronik_aletler_dekupaj_testere',
      ],
      bonusType: SetBonusType.workshopSpeed,
      bonusMultiplier: 1.35,
      cashReward: 1600,
      reputationReward: 380,
      badgeIcon: 'electrical_services',
    ),

    ItemSetModel(
      id: 'set_cozy_living_suite',
      nameTr: 'Masif Ahşap & Konforlu Salon Takımı',
      nameEn: 'Rustic Wood & Comfort Living Suite',
      descriptionTr: 'Meşe yemek masası, kadife kanepe, berjer koltuk, orta sehpa ve abajur masa lambası.',
      descriptionEn: 'Heavy oak dining table, velvet sofa, wingback armchair, coffee table and brass table lamp.',
      category: 'cesitli_mobilyalar',
      rarity: SetRarity.common,
      requiredItemCodes: [
        'ahsap_mobilya_yemek_masasi',
        'cesitli_mobilyalar_kadife_kanepe',
        'cesitli_mobilyalar_berjer_koltuk',
        'cesitli_mobilyalar_orta_sehpa',
        'cesitli_mobilyalar_abajur_lamba',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 1.30,
      cashReward: 1200,
      reputationReward: 250,
      badgeIcon: 'chair',
    ),

    ItemSetModel(
      id: 'set_home_appliances_comfort',
      nameTr: 'Ev Elektroniği & Beyaz Eşya Konforu',
      nameEn: 'Vintage & Modern Home Comfort',
      descriptionTr: 'Retro buzdolabı, çamaşır makinesi, mikrodalga, dikey süpürge ve filtre kahve makinesi.',
      descriptionEn: 'Retro refrigerator, front-load washer, microwave, upright vacuum and drip coffee maker.',
      category: 'beyaz_esya',
      rarity: SetRarity.common,
      requiredItemCodes: [
        'beyaz_esya_retro_buzdolabi',
        'beyaz_esya_camasir_makinesi',
        'beyaz_esya_mikrodalga',
        'beyaz_esya_dikey_supurge',
        'beyaz_esya_filtre_kahve_makinesi',
      ],
      bonusType: SetBonusType.saleMultiplier,
      bonusMultiplier: 1.30,
      cashReward: 1350,
      reputationReward: 280,
      badgeIcon: 'kitchen',
    ),

    ItemSetModel(
      id: 'set_executive_corporate_office',
      nameTr: 'Kurumsal Yönetici Bürosu',
      nameEn: 'Corporate Executive Boardroom',
      descriptionTr: 'Dosya dolabı, ergonomik ofis koltuğu, lazer yazıcı, zımba ve delgeç.',
      descriptionEn: 'Tall filing cabinet, ergonomic chair, laser printer, metal stapler and hole puncher.',
      category: 'ofis_ekipmanlari',
      rarity: SetRarity.common,
      requiredItemCodes: [
        'ofis_ekipmanlari_dosya_dolabi',
        'ofis_ekipmanlari_ofis_koltugu',
        'ofis_ekipmanlari_yazici',
        'ofis_ekipmanlari_zimba',
        'ofis_ekipmanlari_delgec',
      ],
      bonusType: SetBonusType.reputationMultiplier,
      bonusMultiplier: 1.25,
      cashReward: 1100,
      reputationReward: 240,
      badgeIcon: 'work',
    ),
  ];

  /// Eşya koduna göre ait olduğu setleri listeleme
  static List<ItemSetModel> getSetsContainingItem(String itemCode) {
    return all.where((s) => s.requiredItemCodes.contains(itemCode)).toList();
  }

  /// ID'ye göre set bulma
  static ItemSetModel? getById(String id) {
    for (final s in all) {
      if (s.id == id) return s;
    }
    return null;
  }
}
